name: Full Build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'
    - name: Full build with quality assurance testing
      run: |
        mvn -B -fae install -Dqa
    - name: Check for any unformatted files
      run: |
        if [ -n "$(git status --porcelain)" ]
        then
           echo "Build modified or reformatted files"
           git status -s
           exit 1
        else
           echo "Clean build with no files modifed or reformatted"
        fi
    - name: Remove SNAPSHOT jars for lighter cache
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
